### ISSUE TITLE
Swipe to refresh and nested scrolling in Turbo web view conflicts

### ISSUE THREAD

**Issue by annajeanine** [hotwired/turbo-android#243] opened 2022-09-02 07:22 UTC
I'm experiencing a scrolling issue with Turbo Android. 

The situation is as following:
https://user-images.githubusercontent.com/17251777/188081028-0399329e-7be1-4030-b3fd-7a64d7cebe23.mov

When the user wants to scroll up in the modal drop down, the pull to refresh is triggered in the `TurboSwipeRefreshLayout`. This issue can be resolved with a event listener on the `TurboSwipeRefreshLayout` if this is enabled when the `scrollY == 0`. But, the `TurboSwipeRefreshLayout` cannot be accessed from outside of the package as it's an internal class. 

Has anyone else experienced this problem? Is it resolvable without forking the package?

**Comment by annajeanine** [comment] 2022-11-14 13:52
Any update on this?

**Comment by KarishmaAlignable** [comment] 2022-11-28 06:57
I am facing similar issue. Have you found any solution yet.

**Comment by annajeanine** [comment] 2022-11-28 07:40
> I am facing similar issue. Have you found any solution yet.

No unfortunately not yet!

**Comment by connorbey13** [comment] 2023-02-16 01:30
I found a workaround by adding JS to my modal from here: https://stackoverflow.com/a/71313997. This isn't an issue on turbo-ios. May need to be fixed in Android WebView itself?

**Comment by jayohms** [comment] 2024-02-24 15:40
Closing this as duplicate of https://github.com/hotwired/turbo-android/issues/294 since it has reproducible details.

**Closed by jayohms** 2024-02-24 15:40 UTC
